# Generated by Django 5.0.4 on 2024-05-18 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0003_alter_patient_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_iin', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinicApp.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='patient_iin', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='iin',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='IIN'),
        ),
    ]
