# Generated by Django 5.0.4 on 2024-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0006_alter_doctor_phone_number_alter_doctor_working_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(choices=[('Пон', 'Monday'), ('Вто', 'Tuesday'), ('Сре', 'Wednesday'), ('Чет', 'Thursday'), ('Пят', 'Friday'), ('Суб', 'Saturday'), ('Вос', 'Sunday')], default='Пон, Вто, Сре, Чет, Пят, Суб, Вос', max_length=28),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
