# Generated by Django 5.0.4 on 2024-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0009_alter_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
