# Generated by Django 5.0.4 on 2024-05-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0010_alter_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
