# Generated by Django 5.0.4 on 2024-05-18 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinicApp', '0012_alter_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='patient_iin', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinicApp.patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='doctor_groups', related_query_name='doctor', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='doctor_permissions', related_query_name='doctor', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='patient_groups', related_query_name='patient', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='patient_permissions', related_query_name='patient', to='auth.permission'),
        ),
    ]
