# Generated by Django 5.0.4 on 2024-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinicApp', '0016_remove_doctor_groups_remove_doctor_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$WE2S42nmp2Y3s1sfdEyx70$B5wkq2HNmDiYpg0YYsEg0+5EWmVLYECOjgas9I/otI0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
