# Generated by Django 5.0.4 on 2024-05-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0018_doctor_groups_doctor_is_active_doctor_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
    ]
