# Generated by Django 5.0.4 on 2024-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0019_remove_doctor_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(choices=[('Пон', 'Monday'), ('Вто', 'Tuesday'), ('Сре', 'Wednesday'), ('Чет', 'Thursday'), ('Пят', 'Friday'), ('Суб', 'Saturday'), ('Вос', 'Sunday')], default='Пон, Вто, Сре, Чет, Пят, Суб, Вос', max_length=128),
        ),
    ]
