# Generated by Django 5.0.4 on 2024-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinicApp', '0020_doctor_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='doctor_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='doctor_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='patient_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='patient_set', to='auth.permission'),
        ),
    ]
